import type { Vehicle } from '@/types'

export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: '1',
    brand: 'Volkswagen',
    model: 'Golf',
    version: '2.0 TDI 150CV DSG7 Life',
    year: 2022,
    kilometers: 35420,
    price: 22900,
    original_price: 25500,
    monthly_fee: 348,
    fuel_type: 'Diésel',
    transmission: 'Automático',
    color: 'Gris Platino',
    location: 'Madrid',
    description:
      'Volkswagen Golf en impecable estado. Un único propietario. Revisiones realizadas en concesionario oficial Volkswagen. Incluye pack Winter, asientos calefactados, navegador, cámara trasera y sensor de aparcamiento. Listo para entregar.',
    dgt_label: 'C',
    images: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 150,
    doors: 5,
    seats: 5,
    owners: 1,
  },
  {
    id: '2',
    brand: 'Toyota',
    model: 'RAV4',
    version: 'Hybrid 2.5 222CV AWD-i GR Sport',
    year: 2023,
    kilometers: 18500,
    price: 36900,
    original_price: 41500,
    monthly_fee: 561,
    fuel_type: 'Híbrido',
    transmission: 'Automático',
    color: 'Blanco Perla',
    location: 'Barcelona',
    description:
      'Toyota RAV4 Hybrid GR Sport casi nuevo. Garantía Toyota hasta 2027. Techo solar panorámico, cuero, head-up display, parking automático. Bajo consumo (5,8L/100km). Ideal para ZBE con etiqueta ECO.',
    dgt_label: 'ECO',
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1493238792000-8113da705763?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 222,
    doors: 5,
    seats: 5,
    owners: 1,
  },
  {
    id: '3',
    brand: 'SEAT',
    model: 'León',
    version: '1.5 TSI EVO 130CV FR',
    year: 2021,
    kilometers: 48200,
    price: 18500,
    original_price: 21000,
    monthly_fee: 281,
    fuel_type: 'Gasolina',
    transmission: 'Manual',
    color: 'Rojo Desire',
    location: 'Valencia',
    description:
      'SEAT León FR en perfecto estado con historial de mantenimiento completo. Full LED, llantas 18", volante multifunción, sistema de navegación y conectividad Full Link. Sin golpes, impecable.',
    dgt_label: 'C',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 130,
    doors: 5,
    seats: 5,
    owners: 1,
  },
  {
    id: '4',
    brand: 'BMW',
    model: 'Serie 3',
    version: '320d xDrive 190CV M Sport',
    year: 2021,
    kilometers: 54000,
    price: 31900,
    original_price: 37500,
    monthly_fee: 485,
    fuel_type: 'Diésel',
    transmission: 'Automático',
    color: 'Azul Portimao',
    location: 'Madrid',
    description:
      'BMW Serie 3 M Sport con tracción integral xDrive. Paquete M exterior e interior, techo solar, cuero Dakota, head-up display, parking assistant. Historial completo en BMW AG. Ideal para autopista.',
    dgt_label: 'C',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 190,
    doors: 4,
    seats: 5,
    owners: 2,
  },
  {
    id: '5',
    brand: 'Kia',
    model: 'Sportage',
    version: '1.6 T-GDI 265CV Hybrid AWD GT Line',
    year: 2023,
    kilometers: 22000,
    price: 29900,
    original_price: 34000,
    monthly_fee: 455,
    fuel_type: 'Híbrido',
    transmission: 'Automático',
    color: 'Gris Gravity',
    location: 'Sevilla',
    description:
      'Kia Sportage GT Line Hybrid AWD con garantía oficial Kia 7 años. Pantalla doble curva 12.3", asientos ventilados, techo panorámico solar, BOSE Sound. Etiqueta ECO. Entrega inmediata.',
    dgt_label: 'ECO',
    images: [
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 265,
    doors: 5,
    seats: 5,
    owners: 1,
  },
  {
    id: '6',
    brand: 'Renault',
    model: 'Clio',
    version: '1.0 TCe 100CV Intens',
    year: 2022,
    kilometers: 31500,
    price: 14900,
    original_price: 17200,
    monthly_fee: 226,
    fuel_type: 'Gasolina',
    transmission: 'Manual',
    color: 'Blanco Glacial',
    location: 'Bilbao',
    description:
      'Renault Clio Intens con todos los extras. Easy Link 9.3", cámara 360°, sensores de aparcamiento, control de crucero adaptativo, frenado de emergencia. Económico y práctico para ciudad.',
    dgt_label: 'C',
    images: [
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 100,
    doors: 5,
    seats: 5,
    owners: 1,
  },
  {
    id: '7',
    brand: 'Tesla',
    model: 'Model 3',
    version: 'Standard Range Plus AWD',
    year: 2022,
    kilometers: 41000,
    price: 34500,
    original_price: 42000,
    monthly_fee: 524,
    fuel_type: 'Eléctrico',
    transmission: 'Automático',
    color: 'Negro Sólido',
    location: 'Madrid',
    description:
      'Tesla Model 3 AWD con Autopilot completo. Autonomía 500km. Pantalla 15.4", OTA updates, Supercharger incluido. Un propietario, siempre en garaje privado. Batería al 96% de capacidad.',
    dgt_label: '0',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 351,
    doors: 4,
    seats: 5,
    owners: 1,
  },
  {
    id: '8',
    brand: 'Audi',
    model: 'A3',
    version: 'Sportback 35 TFSI 150CV S line',
    year: 2022,
    kilometers: 28700,
    price: 27500,
    original_price: 31000,
    monthly_fee: 418,
    fuel_type: 'Gasolina',
    transmission: 'Automático',
    color: 'Gris Nano',
    location: 'Barcelona',
    description:
      'Audi A3 Sportback S line prácticamente nuevo. MMI Plus con pantalla táctil 10.1", asientos deportivos, iluminación ambiental LED, Virtual Cockpit Plus. Historial Audi Service completo.',
    dgt_label: 'C',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 150,
    doors: 5,
    seats: 5,
    owners: 1,
  },
  {
    id: '9',
    brand: 'Hyundai',
    model: 'Tucson',
    version: '1.6 CRDI 136CV 48V Maxx DCT',
    year: 2021,
    kilometers: 62000,
    price: 23900,
    original_price: 27500,
    monthly_fee: 363,
    fuel_type: 'Diésel',
    transmission: 'Automático',
    color: 'Plata Shimmering',
    location: 'Zaragoza',
    description:
      'Hyundai Tucson Maxx en excelente estado. SmartSense (frenada emergencia, mantenimiento carril, asistente carretera), pantalla 10.25", conexión inalámbrica. Garantía Hyundai activa.',
    dgt_label: 'C',
    images: [
      'https://images.unsplash.com/photo-1493238792000-8113da705763?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format&fit=crop&q=80',
    ],
    model_3d_url: null,
    status: 'available',
    created_at: new Date().toISOString(),
    horsepower: 136,
    doors: 5,
    seats: 5,
    owners: 2,
  },
]

export function getVehicleById(id: string): Vehicle | undefined {
  return DEMO_VEHICLES.find((v) => v.id === id)
}
